## Imports 

In [1]:
import numpy as np 
import sympy.geometry as sp
from time import clock 

## Creating Sympy polygons

In [2]:
p1, p2, p3, p4 = [(0, 0), (1, 0), (5, 1), (0, 1)]
p5, p6, p7 = [(3, 2), (1, -1), (0, 2)]
pol1 = sp.Polygon(p1, p2, p3, p4)
pol2 = sp.Polygon(p5,p6, p7)

r = pol1.intersection(pol2)
polr = sp.Polygon(*r)
print(polr)

Polygon(Point2D(1/3, 1), Point2D(2/3, 0), Point2D(9/5, 1/5), Point2D(7/3, 1))


## Implementation in python

In [3]:
P = np.array(([0,0], [1,1], [2,5], [5,9], [-5,7]))
l = len(P)
a, b, code =   'v', *[None, [0,0]] 
print(a)
print(b)
print(code)
print(l)

v
None
[0, 0]
5


In [4]:
# SegSegInt: Finds the point of intersection p between two closed
# segments ab and cd.  Returns p and a char with the following meaning:
#   'e': The segments collinearly overlap, sharing a point.
#   'v': An endpoint (vertex) of one segment is on the other segment,
#        but 'e' doesn't hold.
#   '1': The segments intersect properly (i.e., they share a point and
#        neither 'v' nor 'e' holds).
#   '0': The segments do not intersect (i.e., they share no points).
# Note that two collinear segments that share just one point, an endpoint
# of each, returns 'e' rather than 'v' as one might expect.

def segsegint(a1, a, b1, b):
    # For math reference see https://stackoverflow.com/questions/563198/whats-the-most-efficent-way-to-calculate-where-two-line-segments-intersect
    # segment1 = (p, p+r) =  p + t*r 
    # segment2 = (q, q+s) =  q + u*s , parametric form

    # Line intersects if there is t and u, so that 
    # p + t*r = q + u*s
    # Or, using cross product with pt2
    # t*(r X s) = (q - p) X s
    
    code = '?'
    p = a1
    q = b1
    r = (a - a1)
    s = (b - b1)
    r_cross_s = np.cross(r, s) 
    
    if r_cross_s == 0:
        if np.cross(q-p, r) == 0:
            # Segments are colinear
            code = 'e'
            seg = return_overlapping(p, q, r, s)
            return code, seg[0], seg[1]
            
        else:
            # Segments are parallel and non-intersecting
            code = 0
            return code, None, None

    t = np.cross(q-p, s) / r_cross_s
    u = np.cross(q-p, r) / r_cross_s

    if (0 <= t <= 1) and (0 <= u <= 1):
        #Segments intersect in one point
        if t==0 or t==1 or u==0 or u==1:
            code = 'v'
        else:
            code = 1
        return code, p + t*r, None
    else:
        # Segments do not intersect 
        code = 0
        return code, None, None
    
def return_overlapping(p,q,r,s):
    
    t0 = np.dot(q-p,r)/np.dot(r,r)
    t1 = np.dot(q+s-p,r)/np.dot(r,r)
    seg = []
    
    if (np.dot(s,r) >= 0):
        
        if t1 < 0 or t0 > 1:
            print("Here1")
            return [None, None]
        elif t1 == 0:
            print("Here2")
            return (p, None)
        elif t0 == 1:
            print("Here3")
            return (p+r, None)
        if (0 < t0 < 1):
            print("Here4")
            seg.append(p+t0*r)
        elif t0 <= 0: 
            print("Here5")
            seg.append(p) 
        if (0 < t1 < 1):
            print("Here6")
            seg.append(p+t1*r)
        elif t1 >= 1: 
            print("Here7")
            seg.append(p+r)
            

    elif (np.dot(s,r) < 0):
        if t0 < 0 or t1 > 1:
            print("here1")
            return [None, None]
        elif t0 == 0:
            print("here2")
            return (p, None)
        elif t1 == 1:
            print("here3")
            return (p+r, None)
        if (0 < t1 < 1):
            print("here4")
            seg.append(p+t1*r)
        elif t1 <= 0: 
            print("here5")
            seg.append(p) 
        if (0 < t0 < 1):
            print("here6")
            seg.append(p+t0*r)        
        elif t0 >= 1:
            print("here7")
            seg.append(p+r)
                    
    return seg
    

In [5]:
P1 = np.array([5,1])
P2 = np.array([0,1])
Q1 = np.array([3,2])
Q2 = np.array([0,2])

code, p, q = segsegint(P1, P2, Q1, Q2)
print(code, p, q)

0 None None


In [6]:
def inout(p, inflag, aHB, bHA):
    #Add point
    I.append(p)
    
    # Update inflag
    if aHB > 0:
        return 'Pin'
    elif bHA > 0:
        return 'Qin'
    else:     #Keep status quo
        return inflag

In [7]:
def advance(a, aa, n, inside, v):
    if inside:
        # Add point
        #I.append(v)
        #print("Found point {} of polygon!".format(v))
        pass
    aa += 1
    return (a+1) % n, aa

In [8]:
def area_sign(o, a, b):
    '''
    Verify if the cross product of
    oa X ob is positive, negative or zero
    o stands of origin, a and b are vectors
    '''
    A = a - o 
    B = b - o 
    area = np.cross(A, B)
    
    if area > 0:
        return 1 
    elif area < 0:
        return -1
    else:
        return 0 

In [13]:
def convex_intersect(P, Q):
    
    # Inicializing variables
    a, b = 0, 0              # Indices of P and Q respectivaly
    aa, ba, = 0, 0           # Advvances on a and b
    n, m = len(P), len(Q)    # Number of vertices of polygons
    inflag = 'Unknow'        # Which polygon is 'inside' 
    FirstPoint = True 
    global i 
    i = 0 #test
    global I 
    I = []  # The intersection polygon
    
    # Main loop
    while ((aa < n) or (ba < m)) and (aa < 2*n) and (ba < 2*m) :   #If both looped or one looped twice through polygon
        i += 1
        # a-1 and b-1, respectivaly 
        a1 = (a + n - 1) % n
        b1 = (b + m - 1) % m 
        
        # A and B are the subvectors that describe a1 to a (the edge of polygon)
        A = P[a] - P[a1]
        B = Q[b] - Q[b1]
      
        # Cheching cross products to predict advance
        origin = np.array([0, 0])
        cross = area_sign(origin, A, B)
        aHB = area_sign(Q[b1], Q[b], P[a])  # a is in the halfplane to the left of B
        bHA = area_sign(P[a1], P[a], Q[b])  # b is in the halfplane to the left of A
        #print("Cross", cross)
        
        # If A and B intersect, change the inflag 
        # code is the kind of intersection, p and q are the intersetion points, if exists
        code, p, q = segsegint(P[a1], P[a], Q[b1], Q[b])
        if code == 1 or code =='v':
            if inflag == 'Unknow' and FirstPoint:
                aa, ab = 0, 0 
                FirstPoint = False 
                p0 = p    # p0 is the first point
                #I.append(p0)
            inflag = inout(p, inflag, aHB, bHA)
        
        # ADVANCE RULES
        
        # Special case: A & B overlap and oppositely oriented
        if code == 'e' and np.dot(A, B) < 0:
            raise SystemExit
        
        # Special case: A & B parallel and separated
        if cross == 0 and aHB < 0 and bHA < 0:
            print("P and Q are disjoint")
            raise SystemExit
        
        # Special case: A & B are collinear
        elif cross == 0 and aHB == 0 and bHA == 0:
            if inflag == 'Pin':
                b, ba = advance(b, ba, m, inflag=='Qin', Q[b])
            else:
                a, aa = advance(a, aa, n, inflag=='Pin', P[a])
        
        # Generic cases
        elif cross >= 0:
            if bHA > 0:
                a, aa = advance(a, aa, n, inflag=='Pin', P[a])
            else:
                b, ba = advance(b, ba, m, inflag=='Qin', Q[b])
        
        else:  # cross<0
            if aHB > 0:
                b, ba = advance(b, ba, m, inflag=='Qin', Q[b])
            else:
                a, aa = advance(a, aa, n, inflag=='Pin', P[a])
                
    if not FirstPoint:  # If found at least one point
        # I.append(p0)
        pass
        
    if inflag == "Unknow":
        print("The boundaries of P and Q do not cross")
    
    return(I)

P = np.array([(5, 1), (0, 1), (0, 0), (1, 0)])
Q = np.array([(3, 2), (0, 2), (1, -1)])
convex_intersect(P, Q)


[array([1.8, 0.2]),
 array([2.33333333, 1.        ]),
 array([0.33333333, 1.        ]),
 array([0.66666667, 0.        ])]

In [ ]:
c, p, q = segsegint(np.array([0, 1]), np.array([0, 0]), np.array([0, 2]), np.array([1, -1]))
print(c,p,q)

In [ ]:
A = np.array([2, 2])
B = np.array([1, 1])
C = A - B
C